In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = [['nissan', 2010, 10000], ['honda', 2012, 15000], ['toyota', 2015, 20000]]

df = pd.DataFrame(data, columns=['Make', 'Year', 'Price'])

In [ ]:
df.head(n = 1)

In [ ]:
df.Year

In [ ]:
import pandas as pd
import numpy as np

cars_data = {
    "Car_ID": [101, 102, 103, 104, 105],
    "Brand": ["Toyota", "Honda", "Tesla", "BMW", "Hyundai"],
    "Model": ["Camry", "Civic", "Model 3", "X5", "Creta"],
    
    # Missing values added
    "Year": [2022, 2021, 2023, np.nan, 2024],
    
    "Color": ["White", "Black", "Red", "Blue", "Grey"],
    "Fuel_Type": ["Petrol", "Diesel", "Electric", "Diesel", "Petrol"],
    "Transmission": ["Automatic", "Manual", "Automatic", "Automatic", "Manual"],
    
    # Missing values
    "Engine_CC": [2500, 1800, 0, np.nan, 1500],
    "Mileage_kmpl": [15, 20, np.nan, 12, 18],
    
    "Price_USD": [30000, 25000, 45000, 60000, 22000],
    "Horsepower": [203, 158, 283, 335, 115],
    
    # Missing values
    "Seating_Capacity": [5, np.nan, 5, 7, 5],
    "Safety_Rating": [np.nan, 5, 5, 5, 4],
    
    "Sunroof": [True, False, True, True, False],
    "Navigation_System": [True, True, True, True, False]
}

# Create DataFrame
df = pd.DataFrame(cars_data)

print(df)

In [ ]:
df = pd.DataFrame(cars_data)

In [ ]:
df

In [ ]:
df.head(n = 4)

In [ ]:
df[["Color", "Price_USD"]    ]

In [ ]:
df

In [ ]:
df['model id'] =[238,32,32,24,214]

In [ ]:
df

In [ ]:
del df['model id']

In [ ]:
df

In [ ]:
df.index

In [ ]:
df.loc[1]

In [ ]:
df[df['Year'] > 2023]

In [ ]:
df

In [ ]:
'STRr'.lower()

In [ ]:
df['Model'] = df['Model'].str.replace(' ', '_').str.lower()

In [ ]:
df

In [ ]:
df['Price_USD'].describe()

In [ ]:
df.describe().round(0)

In [ ]:
df['Model'].nunique()

In [ ]:
df.isnull().sum()

In [ ]:
df.groupby('Transmission').Price_USD.mean()

In [ ]:
df.Price_USD.values

In [ ]:
df.to_dict(orient='records')

In [ ]:
df.to_json()

In [ ]:
 pd.__version__

In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [ ]:
df

In [60]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [ ]:
df.values

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
df.nunique['fuel_type']

In [61]:
df.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

In [36]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [40]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [44]:
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

SyntaxError: invalid syntax (4154924484.py, line 1)

In [62]:
df['horsepower']

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

/* Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No
*/

In [63]:

mode_value = df["horsepower"].mode()[0]
mode_value

np.float64(152.0)

In [64]:
df['horsepower_new'] = df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

/tmp/ipykernel_21105/2539620148.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['horsepower_new'] = df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

median =  149 
mode = 152

In [66]:
df['horsepower_new'].median()

np.float64(152.0)

In [67]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg,horsepower_new
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729,159.0
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217,97.0
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341,78.0
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736,152.0
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369,140.0

In [73]:
df = df.groupby('origin').get_group('Asia')

In [74]:
df.head(7)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg,horsepower_new
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554,174.0
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820,145.0
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091,160.0
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083,197.0
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730,133.0
34,150,2.0,149.0,2844.227534,17.3,2014,Asia,Diesel,Front-wheel drive,0.0,15.353788,149.0
38,190,5.0,158.0,3761.994038,NaN,2019,Asia,Gasoline,Front-wheel drive,1.0,11.645724,158.0

In [76]:
df[['vehicle_weight', 'model_year']]

KeyError: ('vehicle_weight', 'model_year')